version: '3.3'
services:
  k6:
    image: grafana/k6
    container_name: k6
    volumes:
      - '${PWD}/src:/scripts'
    environment:
      - API_SUBSCRIPTION_KEY=${sub_key}
      - VARS=/${env}.environment.json
      - TEST_TYPE=/scripts/test-types/${type}.json
      - K6_OUT=influxdb=http://nginx:8086/${db_name}
      - ID_PSP=${id_psp}
      - ID_BROKER_PSP=${id_broker_psp}
      - ID_CHANNEL=${id_channel}
      - ID_CI=${id_ci}
      - ID_BROKER_CI=${id_broker_ci}
      - ID_STATION=${id_station}
      - NOTICE_NUMBER=${notice_number}
      - HOST_URL=${host_url}
      - HOST_PORT=${host_port}
      - HOST_PATH=${host_path}
    command: run /scripts/${script}.js
    depends_on:
      - nginx

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - '${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - "8086:8086"
      - "80:80"

