# azure-pipelines.yml
trigger: none

parameters:
  - name: "ENVIRONMENT"
    displayName: "Environment"
    type: string
    values:
      - "dev"
      - "uat"
    default: "uat"
  - name: "ID_PSP"
    displayName: "ID_PSP"
    type: string
    default: "-"
  - name: "ID_BROKER_PSP"
    displayName: "ID_BROKER_PSP"
    type: string
    default: "-"
  - name: "ID_CHANNEL"
    displayName: "ID_CHANNEL"
    type: string
    default: "-"
  - name: "ID_CI"
    displayName: "ID_CI"
    type: string
    default: "77777777777"
  - name: "ID_BROKER_CI"
    displayName: "ID_BROKER_CI"
    type: string
    default: "77777777777"
  - name: "ID_STATION"
    displayName: "ID_STATION"
    type: string
    default: "77777777777_08"
  - name: "NOTICE_NUMBER"
    displayName: "NOTICE_NUMBER"
    type: string
    default: "346111111112222222"
  - name: "HOST_URL"
    displayName: "TARGET_HOST"
    type: string
    default: "mockec.ddns.net"
  - name: "HOST_PORT"
    displayName: "TARGET_PORT"
    type: number
    default: "8080"
  - name: "HOST_PATH"
    displayName: "TARGET_PATH"
    type: string
    default: "/servizi/PagamentiTelematiciRPT"
  - name: "TEST_TYPE"
    displayName: "Test type"
    type: string
    values:
      - "load"
      - "ramping"
      - "single"
      - "smoke"
      - "spike"
      - "stress"
      - "constant"
    default: "constant"
  - name: "SCRIPT"
    displayName: "Script name"
    type: string
    values:
      - node_pa
      - psp_node_pa
    default: "node_pa"
  - name: "DEBUG"
    displayName: "Enable debug in script"
    type: boolean
    default: false

variables:
  ${{ if eq(parameters['ENVIRONMENT'], 'dev') }}:
    API_SUBSCRIPTION_KEY: $(DEV_API_SUBSCRIPTION_KEY)
    poolImage: 'pagopa-dev-loadtest-linux'
  ${{ if eq(parameters['ENVIRONMENT'], 'uat') }}:
    API_SUBSCRIPTION_KEY: $(UAT_API_SUBSCRIPTION_KEY)
    poolImage: 'pagopa-uat-loadtest-linux'

pool:
  name: $(poolImage)

steps:
  - script: |
      cd ./performance-test/src
      docker pull grafana/k6
    displayName: Pull k6 image

  - script: |
      cd ./performance-test
      sh ./run_performance_test.sh ${{ parameters.ENVIRONMENT }} ${{ parameters.TEST_TYPE }} ${{ parameters.SCRIPT }} pagopanodeforwarder $(API_SUBSCRIPTION_KEY) ${{ parameters.ID_PSP }} ${{ parameters.ID_BROKER_PSP }} ${{ parameters.ID_CHANNEL }} ${{ parameters.ID_CI }} ${{ parameters.ID_BROKER_CI }} ${{ parameters.ID_STATION }} ${{ parameters.NOTICE_NUMBER }} ${{ parameters.HOST_URL }} ${{ parameters.HOST_PORT }} ${{ parameters.HOST_PATH }} ${{ parameters.DEBUG }}
    displayName: Run k6 ${{ parameters.SCRIPT }} on ${{ parameters.ENVIRONMENT }}
